// <auto-generated />
using System;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610064053_AddStockImportReceipts")]
    partial class AddStockImportReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DanhGiaTrungBinh")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaSanXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoBanDaMuon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhGiaTrungBinh = 0.0,
                            NhaSanXuat = "NXB BKHN",
                            SoBanDaMuon = 0,
                            SoLuong = 10,
                            SoLuotDanhGia = 0,
                            TacGia = "Nguyễn Văn A",
                            TenSach = "Lập trình C#"
                        },
                        new
                        {
                            Id = 2,
                            DanhGiaTrungBinh = 0.0,
                            NhaSanXuat = "NXB Tin học",
                            SoBanDaMuon = 0,
                            SoLuong = 8,
                            SoLuotDanhGia = 0,
                            TacGia = "Trần Thị B",
                            TenSach = "SQL Server"
                        },
                        new
                        {
                            Id = 3,
                            DanhGiaTrungBinh = 0.0,
                            NhaSanXuat = "NXB Công nghệ",
                            SoBanDaMuon = 0,
                            SoLuong = 12,
                            SoLuotDanhGia = 0,
                            TacGia = "Lê Văn C",
                            TenSach = "AI cơ bản"
                        });
                });

            modelBuilder.Entity("CatalogService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Truyện ngắn"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tiểu thuyết"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Văn học Việt Nam"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Văn học nước ngoài"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kỹ năng sống"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lập trình"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Khoa học máy tính"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Trí tuệ nhân tạo"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Khoa học"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Toán học"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Vật lý"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Hóa học"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sinh học"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kinh tế"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Quản trị kinh doanh"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tài chính"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Kế toán"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Luật"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Y học"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Giáo dục"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Giáo trình"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ngoại ngữ"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Tiếng Anh"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lịch sử"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Địa lý"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Chính trị"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Triết học"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Tâm lý học"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Nghệ thuật"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Âm nhạc"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Du lịch"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Ẩm thực"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Tôn giáo"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Truyện tranh"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Light Novel"
                        });
                });

            modelBuilder.Entity("CatalogService.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CatalogService.Models.StockImportItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("StockImportItems");
                });

            modelBuilder.Entity("CatalogService.Models.StockImportReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("StockImportReceipts");
                });

            modelBuilder.Entity("CatalogService.Models.StockImportItem", b =>
                {
                    b.HasOne("CatalogService.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CatalogService.Models.StockImportReceipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CatalogService.Models.StockImportReceipt", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
