// <auto-generated />
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603014136_AddBookRating")]
    partial class AddBookRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DanhGiaTrungBinh")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaSanXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoBanDaMuon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhGiaTrungBinh = 0.0,
                            NhaSanXuat = "NXB BKHN",
                            SoBanDaMuon = 0,
                            SoLuong = 10,
                            SoLuotDanhGia = 0,
                            TacGia = "Nguyễn Văn A",
                            TenSach = "Lập trình C#"
                        },
                        new
                        {
                            Id = 2,
                            DanhGiaTrungBinh = 0.0,
                            NhaSanXuat = "NXB Tin học",
                            SoBanDaMuon = 0,
                            SoLuong = 8,
                            SoLuotDanhGia = 0,
                            TacGia = "Trần Thị B",
                            TenSach = "SQL Server"
                        },
                        new
                        {
                            Id = 3,
                            DanhGiaTrungBinh = 0.0,
                            NhaSanXuat = "NXB Công nghệ",
                            SoBanDaMuon = 0,
                            SoLuong = 12,
                            SoLuotDanhGia = 0,
                            TacGia = "Lê Văn C",
                            TenSach = "AI cơ bản"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
